version: "3.7"

services:
  db:
    image: postgres
    volumes:
       - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_HOST=db

  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_HOST=redis
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver_plus 0.0.0.0:8000 --print-sql
    volumes:
      - .:/social_app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  redis_data: