# Generated by Django 3.2.7 on 2021-09-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislikepost',
            old_name='created_at',
            new_name='disliked_at',
        ),
        migrations.RenameField(
            model_name='likepost',
            old_name='created_at',
            new_name='liked_at',
        ),
    ]
