# Generated by Django 3.2.7 on 2021-09-12 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210912_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='liked_at',
            field=models.DateField(default=datetime.date(2021, 9, 10)),
        ),
    ]
