# Generated by Django 3.2.7 on 2021-09-12 12:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_alter_likepost_liked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikepost',
            name='disliked_at',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='liked_at',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
