# Generated by Django 3.2.7 on 2021-09-12 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20210912_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
