# Generated by Django 3.2.7 on 2021-09-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_socialprofile_last_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialProfile',
        ),
    ]
